// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 avtc <tarasenkov@gmail.com>

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { AgentToolResult } from "@earendil-works/pi-agent-core";
import type {
  ExtensionAPI,
  ExtensionContext,
  ToolDefinition,
  ToolRenderResultOptions,
} from "@earendil-works/pi-coding-agent";
import { afterAll, afterEach, describe, expect, test } from "vitest";
import { KanbanDatabase } from "../../src/kanban/data/kanban-database.js";
import kanbanExtension, { resetInstances, setDatabaseInstance } from "../../src/kanban/kanban-bridge.js";
import { generateSlug } from "../../src/kanban/kanban-server.js";
import { initGitDir } from "../helpers/git-template.js";

const tempDirs: string[] = [];

function createTempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "kanban-add-test-"));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  resetInstances();
});

afterAll(() => {
  for (const dir of tempDirs) {
    try {
      fs.rmSync(dir, { recursive: true, force: true });
    } catch {}
  }
});

describe("add_to_backlog tool execute logic", () => {
  test("creates feature in backlog with slug collision detection", async () => {
    const tempDir = createTempDir();
    const db = await KanbanDatabase.createInMemory();
    const projectId = db.createProject({ name: "test", repoPath: tempDir });

    const slug = generateSlug("Auto Agent Grace Period");

    // Create feature
    const featureId = db.createFeature({
      projectId,
      slug,
      title: "Auto Agent Grace Period",
      description:
        "Important: content generated by LLM, based on user description — " +
        "research and reask user regarding every section and nuances\n\n" +
        "Add a configurable grace period before auto-agent activates a design feature.",
      lane: "backlog",
    });

    expect(featureId).toBeGreaterThan(0);

    const feature = db.getFeature(featureId);
    expect(feature).not.toBeNull();
    expect((feature as NonNullable<typeof feature>).lane).toBe("backlog");
    expect((feature as NonNullable<typeof feature>).title).toBe("Auto Agent Grace Period");
    expect((feature as NonNullable<typeof feature>).description).toContain("Important: content generated by LLM");

    // Slug collision: trying to create again should be detectable
    const existing = db.findFeatureBySlug(slug, projectId);
    expect(existing).not.toBeNull();
    expect((existing as NonNullable<typeof existing>).id).toBe(featureId);
  });

  test("auto-creates project if none exists", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();

    // No project exists yet — simulate auto-creation
    const cwd = "/fake/repo/path";
    const newProjectId = db.createProject({ name: path.basename(cwd), repoPath: cwd });
    expect(newProjectId).toBeGreaterThan(0);

    const project = db.getProject(newProjectId);
    expect(project).not.toBeNull();
    expect((project as NonNullable<typeof project>).name).toBe("path");
  });
});

describe("add_to_backlog tool execute via registered tool", () => {
  test("execute creates feature with LLM note prefix and returns formatted result", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();
    // Don't pre-create a project — the tool will auto-create one via detectProject.
    // detectProject resolves process.cwd() to a git repo path.
    // We inject our test DB so the tool uses it instead of creating a new one.
    setDatabaseInstance(db);

    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog");
    expect(tool).toBeDefined();

    // Execute the tool
    const slug = generateSlug("My New Feature");
    const result = await (tool as ToolDefinition).execute(
      "call-1",
      { slug, title: "My New Feature", description: "A detailed description of the feature." },
      undefined, // signal
      undefined, // onUpdate
      {} as unknown as ExtensionContext, // ctx
    );

    // Verify return value
    expect(result.content).toHaveLength(1);
    expect(result.content[0].type).toBe("text");
    expect((result.content[0] as { text?: string }).text).toContain("Feature added to backlog");
    expect((result.content[0] as { text?: string }).text).toContain("My New Feature");
    expect((result.content[0] as { text?: string }).text).toContain("backlog");

    // Verify the feature was created in the DB with LLM note prefix.
    // Use unscoped lookup (no projectId) since the tool auto-created the project.
    const feature = db.findFeatureBySlug(slug, undefined);
    expect(feature).not.toBeNull();
    expect((feature as NonNullable<typeof feature>).description).toContain("Important: content generated by LLM");
    expect((feature as NonNullable<typeof feature>).description).toContain("A detailed description of the feature.");
    expect((feature as NonNullable<typeof feature>).lane).toBe("backlog");
  });

  test("execute returns error on slug collision", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();
    setDatabaseInstance(db);

    // Create a temp CWD with git repo so detectProject resolves correctly
    const gitTempDir = createTempDir();
    const originalCwd = process.cwd();
    process.chdir(gitTempDir);
    try {
      initGitDir(gitTempDir);

      // Pre-create project with the git repo path so detectProject finds it
      db.createProject({ name: "test", repoPath: gitTempDir });

      const registeredTools = new Map<string, unknown>();
      const api = {
        on() {},
        registerTool(tool: unknown) {
          registeredTools.set((tool as ToolDefinition).name, tool);
        },
        registerCommand() {},
        appendEntry() {},
        sendUserMessage() {},
      } as unknown as ExtensionAPI;

      const extension = kanbanExtension;
      await extension(api, null);

      const tool = registeredTools.get("add_to_backlog");
      const collisionSlug = generateSlug("Duplicate Feature");

      // First call — creates the feature
      await (tool as ToolDefinition).execute(
        "call-1",
        { slug: collisionSlug, title: "Duplicate Feature", description: "First one." },
        undefined,
        undefined,
        {} as unknown as ExtensionContext,
      );

      // Second call — same slug, should detect collision
      const result = await (tool as ToolDefinition).execute(
        "call-2",
        { slug: collisionSlug, title: "Duplicate Feature", description: "Should fail." },
        undefined,
        undefined,
        {} as unknown as ExtensionContext,
      );

      expect((result.content[0] as { text?: string }).text).toContain("already exists");
    } finally {
      process.chdir(originalCwd);
    }
  });

  test("execute with empty title generates slug and creates feature", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();
    setDatabaseInstance(db);

    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog");
    const today = new Date().toISOString().slice(0, 10);
    const explicitSlug = `${today}-untitled`;
    const result = await (tool as ToolDefinition).execute(
      "call-1",
      { slug: explicitSlug, title: "", description: "Some description" },
      undefined,
      undefined,
      {} as unknown as ExtensionContext,
    );

    // Should create a feature with the explicit slug
    expect((result.content[0] as { text?: string }).text).toContain("Feature added to backlog");
    const feature = db.findFeatureBySlug(explicitSlug, undefined);
    expect(feature).not.toBeNull();
    expect((feature as NonNullable<typeof feature>).lane).toBe("backlog");
  });

  test("execute with empty description still prefixes LLM note", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();
    setDatabaseInstance(db);

    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog");
    const slug = generateSlug("Empty Desc Feature");
    const result = await (tool as ToolDefinition).execute(
      "call-1",
      { slug, title: "Empty Desc Feature", description: "" },
      undefined,
      undefined,
      {} as unknown as ExtensionContext,
    );

    expect((result.content[0] as { text?: string }).text).toContain("Feature added to backlog");
    const feature = db.findFeatureBySlug(slug, undefined);
    expect(feature).not.toBeNull();
    // Should have LLM note prefix even with empty description
    expect((feature as NonNullable<typeof feature>).description).toContain("Important: content generated by LLM");
  });

  test("auto-created project has correct name and repoPath", async () => {
    createTempDir();
    const db = await KanbanDatabase.createInMemory();
    setDatabaseInstance(db);

    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog");
    const slug = generateSlug("Project Test Feature");
    await (tool as ToolDefinition).execute(
      "call-1",
      { slug, title: "Project Test Feature", description: "Testing project auto-creation." },
      undefined,
      undefined,
      {} as unknown as ExtensionContext,
    );

    // Verify the feature was created and assigned to a project
    const feature = db.findFeatureBySlug(slug, undefined);
    expect(feature).not.toBeNull();
    expect((feature as NonNullable<typeof feature>).lane).toBe("backlog");

    // Verify the project exists (either auto-created or found by detectProject)
    const project = db.getProject((feature as NonNullable<typeof feature>).project_id);
    expect(project).not.toBeNull();
    const cwd = process.cwd();
    expect((project as NonNullable<typeof project>).name).toBe(path.basename(cwd));
    expect((project as NonNullable<typeof project>).repo_path.replace(/\\/g, "/").toLowerCase()).toBe(
      cwd.replace(/\\/g, "/").toLowerCase(),
    );
  });

  test("renderCall displays title with tool name", async () => {
    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog") as unknown as ToolDefinition;
    expect(tool.renderCall).toBeDefined();

    const theme = {
      fg: (_name: string, text: string) => `<${_name}>${text}</${_name}>`,
      bold: (text: string) => `<b>${text}</b>`,
    } as unknown as Parameters<NonNullable<ToolDefinition["renderCall"]>>[1];
    const result = (tool as ToolDefinition).renderCall?.(
      { slug: "my-feature-slug", title: "My Feature" },
      theme,
      undefined as unknown as Parameters<NonNullable<ToolDefinition["renderCall"]>>[2],
    );
    expect((result as { text?: string }).text).toContain("add_to_backlog");
    expect((result as { text?: string }).text).toContain("my-feature-slug");
  });

  test("renderResult displays success text", async () => {
    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog") as unknown as ToolDefinition;
    expect(tool.renderResult).toBeDefined();

    const theme = {
      fg: (_name: string, text: string) => `<${_name}>${text}</${_name}>`,
    } as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[2];
    const toolResult = {
      content: [{ type: "text", text: "Feature added to backlog!" }],
    } as unknown as AgentToolResult<unknown>;
    const rendered = tool.renderResult?.(
      toolResult,
      {} as ToolRenderResultOptions,
      theme,
      {} as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[3],
    );
    expect((rendered as { text?: string }).text).toContain("Feature added to backlog!");
  });

  test("renderResult returns empty text for non-text content", async () => {
    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog") as unknown as ToolDefinition;
    expect(tool.renderResult).toBeDefined();

    const theme = {
      fg: (_name: string, text: string) => `<${_name}>${text}</${_name}>`,
    } as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[2];
    // Simulate a non-text content result (e.g., image)
    const toolResult = { content: [{ type: "image", data: "..." }] } as unknown as AgentToolResult<unknown>;
    const rendered = tool.renderResult?.(
      toolResult,
      {} as ToolRenderResultOptions,
      theme,
      {} as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[3],
    );
    // Non-text content renders as an empty Text (renderResult must return a Component, not null).
    expect(rendered).toBeDefined();
  });

  test("renderResult renders collision error in error color", async () => {
    const registeredTools = new Map<string, unknown>();
    const api = {
      on() {},
      registerTool(tool: unknown) {
        registeredTools.set((tool as ToolDefinition).name, tool);
      },
      registerCommand() {},
      appendEntry() {},
      sendUserMessage() {},
    } as unknown as ExtensionAPI;

    const extension = kanbanExtension;
    await extension(api, null);

    const tool = registeredTools.get("add_to_backlog") as unknown as ToolDefinition;
    expect(tool.renderResult).toBeDefined();

    const theme = {
      fg: (_name: string, text: string) => `<${_name}>${text}</${_name}>`,
    } as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[2];
    // Simulate a collision error result
    const toolResult = {
      content: [
        {
          type: "text",
          text: `A feature with slug "test" already exists (ID: 42, lane: backlog). Not creating duplicate.`,
        },
      ],
    } as unknown as AgentToolResult<unknown>;
    const rendered = tool.renderResult?.(
      toolResult,
      {} as ToolRenderResultOptions,
      theme,
      {} as unknown as Parameters<NonNullable<ToolDefinition["renderResult"]>>[3],
    );
    expect((rendered as { text?: string }).text).toContain("<error>");
    expect((rendered as { text?: string }).text).toContain("already exists");
  });
});
